### ISSUE TITLE
Completed recipes folder is missing in the download

### ISSUE THREAD

**Issue by eliassal** [TeachingKidsProgramming/TeachingKidsProgramming.Java#19]
Hi, in th video, Getting started - for teachers, you show  a folder named "completed" in src for the teachers which is missing in the download, i browsed the code here as well, it is also missing
thanks for your help

**Comment by lynnlangit** [comment]
This is by design.  The 'working' download (for the classroom and students) does NOT include the answers.  

We have linked the answers for each recipe/lesson in the Penflip (teacher lesson plans) - see http://teachingkidsprogramming.org/courses/ > course01... > 'download lesson plan'

Alternatively, if you, as a teacher, would like to use the recipe code answers to help for your own preparation they are [here](https://github.com/TeachingKidsProgramming/TeachingKidsProgramming.Source.Java/tree/master/src/main/java/org/teachingkidsprogramming/recipes/completed) on Github.
