### ISSUE TITLE
Cannot run the TKP_Launcher.jar on Mac

### ISSUE THREAD

**Issue by ankermarco** [TeachingKidsProgramming/TeachingKidsProgramming.Java#29]
Hi there, I am following your installation instructions on my Macbook. But when I double click to run the TKP_Launcher.jar, I am getting error message as "java.io.FileNotFoundException: /private/var/folders/1b/g32zj9gx6ms1791m5c9zv608000gn/T/hsperfdata_minggap/eclipse_workspace.zip(No such file or directory)"

**Comment by lynnlangit** [comment]
Sorry and thanks for letting us know.  Do you have the `eclipse_workspace.zip` file in your download?  Would it be possible for you to try to unzip it manually.  This type of error is generally due to permissions issues (default settings have to be changed to be able to allow `TKP_Launcher.jar` to unzip a file that was downloaded from the web.  HTH-- Lynn
